"""
`models.capture` module: Class to interact wit the "capture" table.
"""
import uuid

import peewee
from playhouse.sqlite_ext import JSONField

from ..models import AccessKey
from ..utils import get_db


class Capture(peewee.Model):
    """
    "capture" table definition. Helps keep trace of capture processes.
    """

    id_capture = peewee.UUIDField(primary_key=True, null=False, default=uuid.uuid4)

    id_access_key = peewee.ForeignKeyField(model=AccessKey, field="id_access_key", index=True)

    created_timestamp = peewee.TimestampField(utc=True, resolution=1000, null=False)

    started_timestamp = peewee.TimestampField(
        utc=True, resolution=1000, null=True, default=None, index=True
    )

    ended_timestamp = peewee.TimestampField(
        utc=True, resolution=1000, null=True, default=None, index=True
    )

    url = peewee.TextField(null=False)

    callback_url = peewee.TextField(null=True)

    options = JSONField(null=True)
    """JSON object for additional options and parameters (TBD)."""

    status = peewee.CharField(
        max_length=16,
        choices=["pending", "started", "failed", "success"],
        default="pending",
        index=True,
    )
    """Current status can be: "pending", "started", "failed"."""

    stdout_logs = peewee.TextField(null=True)
    """STDOUT Logs generated by the capture software."""

    stderr_logs = peewee.TextField(null=True)
    """STDERR Logs generated by the capture software."""

    summary = JSONField(null=True)
    """JSON object summarizing capture info."""

    class Meta:
        table_name = "capture"
        database = get_db()
